// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1lu7Awv5fLcYO3l3rANU-u36ONnopGAw',
    appId: '1:892408592772:web:7130fe75470aa23eab45d1',
    messagingSenderId: '892408592772',
    projectId: 'quan-ly-phe-duyet-don',
    authDomain: 'quan-ly-phe-duyet-don.firebaseapp.com',
    storageBucket: 'quan-ly-phe-duyet-don.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB91GADFuSIfMhM_NPZiNAO25wxoG62pK8',
    appId: '1:892408592772:ios:f44625971b9a8012ab45d1',
    messagingSenderId: '892408592772',
    projectId: 'quan-ly-phe-duyet-don',
    storageBucket: 'quan-ly-phe-duyet-don.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1lu7Awv5fLcYO3l3rANU-u36ONnopGAw',
    appId: '1:892408592772:web:7cf5028bca38b229ab45d1',
    messagingSenderId: '892408592772',
    projectId: 'quan-ly-phe-duyet-don',
    authDomain: 'quan-ly-phe-duyet-don.firebaseapp.com',
    storageBucket: 'quan-ly-phe-duyet-don.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB91GADFuSIfMhM_NPZiNAO25wxoG62pK8',
    appId: '1:892408592772:ios:f44625971b9a8012ab45d1',
    messagingSenderId: '892408592772',
    projectId: 'quan-ly-phe-duyet-don',
    storageBucket: 'quan-ly-phe-duyet-don.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9K9qhK3DlqVr8z4RsH_cJFTpFetGyI0',
    appId: '1:892408592772:android:f920361d3c3b9a3aab45d1',
    messagingSenderId: '892408592772',
    projectId: 'quan-ly-phe-duyet-don',
    storageBucket: 'quan-ly-phe-duyet-don.firebasestorage.app',
  );
}
